runtime: nodejs20
service: frontend

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  # Menyajikan semua file statis lainnya
  - url: /(.*)
    static_files: \1
    upload: (.*)
